# Generated by Django 6.0.6 on 2026-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('ID_Mascota', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Roedor', 'Roedor'), ('Reptil', 'Reptil'), ('Otro', 'Otro')], max_length=20)),
                ('Raza', models.CharField(blank=True, max_length=50)),
                ('Edad', models.IntegerField()),
                ('Dueno', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('Fecha_Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
